### ISSUE TITLE
findIT

### ISSUE THREAD

**Issue by hjorthjort** [cthit/wishlist#2]
# Description

A portal site for all the services developed by and for the IT section.
# We need it because ...

There are a lot of services right now, and for many students they are discovered randomly, when someone points them to it. If there was a single portal site where one could browse all the services, people would find and use them more.
# Ideas for additional features
- Different sections for different things
  - Core tools like VoteIT, chalmers.it, bookIT, dokument, etc
  - Tutorials: irc.chalmers.it, git.chalmers.it, etc.
  - Added value stuff: hubbIT, eatIT, hueIT, etc 
# I promise that
- [x] I have read and understood the [Readme](https://github.com/cthit/wishlist/blob/master/README.md)
- [x] I believe this suggestion adds value to the IT section

**Comment by jesperlindstrom** [comment]
Preferably build this as a page on chalmers.it or at least have a clearly visible link at chalmers.it to this new service, to make sure that people find it / become aware of it.

**Comment by hjorthjort** [comment]
+1 on giving a clear link on chalmers.it

**Comment by jesperlindstrom** [comment]
Made a repository at https://github.com/cthit/findIT using mat.chalmers.it as base.
